# Copyright (c) 2025 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

---
engines:
  rubocop:
    enabled: true
    exclude_paths:
    - config/engines.yml
  duplication:
    enabled: true
    exclude_paths:
    - config/engines.yml
  metrics:
    enabled: true
    exclude_paths:
    - config/engines.yml
  coverage:
    enabled: true
    exclude_paths:
    - config/engines.yml
languages:
  css:
    extensions:
    - '-css.resource'
exclude_paths:
- '.bundle/**'
- 'spec/**/*'
- 'benchmarks/**/*'
- '*.min.js'
- '**/*.pb.go'
- '**/tests/**'
